"use client";

import { useState } from "react";
import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  Clock,
  FileText,
  Shield,
  X,
  Zap,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type RAGStatus = "green" | "amber" | "red";

interface Answers {
  q1: string[];
  q2: string;
  q3: string;
  q4: string;
  q5: string;
  q6: string;
  q7: string;
}

const HIGH_RISK_DOMAINS = [
  {
    value: "biometric",
    label: "Biometric identification or categorisation of natural persons",
  },
  {
    value: "critical-infra",
    label: "Critical infrastructure (energy, water, transport, finance)",
  },
  {
    value: "education",
    label: "Education, vocational training, or student assessment",
  },
  {
    value: "employment",
    label: "Employment, worker management, or recruitment screening",
  },
  {
    value: "essential-services",
    label:
      "Access to essential private services (credit, insurance, healthcare)",
  },
  {
    value: "law-enforcement",
    label: "Law enforcement, border control, or crime prediction",
  },
  {
    value: "justice",
    label: "Administration of justice or democratic processes",
  },
  {
    value: "none",
    label: "None of the above — my system is general-purpose or low-risk",
  },
];

const RADIO_QUESTIONS = [
  {
    id: "q2" as const,
    article: "Annex III scope",
    title: "Does your AI system autonomously interact with external systems?",
    subtitle:
      "Autonomous agentic operations place additional scrutiny on your system's traceability obligations.",
    options: [
      {
        value: "yes",
        label:
          "Yes — it calls APIs, sends emails, accesses databases, or executes code autonomously",
      },
      {
        value: "supervised",
        label:
          "Partially — it generates recommendations but a human approves each action",
      },
      {
        value: "no",
        label:
          "No — it only generates text responses that humans act on manually",
      },
      { value: "unknown", label: "I'm not sure" },
    ],
  },
  {
    id: "q3" as const,
    article: "Article 12(1)",
    title:
      "Is behavioral logging automatic and independent of the AI system itself?",
    subtitle:
      "Article 12(1) requires logging that the AI system cannot suppress or modify — a diary the agent writes itself does not qualify.",
    options: [
      {
        value: "independent",
        label:
          "Yes — logging happens at infrastructure level; the agent has no write access to its own logs",
      },
      {
        value: "partial",
        label:
          "Partial — we log, but the agent writes its own log entries",
      },
      {
        value: "none",
        label: "No — we have no structured behavioral logging",
      },
      { value: "unknown", label: "I'm not sure" },
    ],
  },
  {
    id: "q4" as const,
    article: "Articles 12 & 15",
    title: "Are your logs cryptographically tamper-evident?",
    subtitle:
      "Articles 12 and 15 require that any modification to a log entry is detectable — tamper-resistant storage alone is not sufficient.",
    options: [
      {
        value: "cryptographic",
        label:
          "Yes — logs are signed by an entity outside the agent's control (Ed25519, hash chains, etc.)",
      },
      {
        value: "partial",
        label:
          "Partial — we use checksums or hashing, but they are generated by the agent itself",
      },
      {
        value: "none",
        label: "No — logs are plain records with no tamper protection",
      },
      { value: "unknown", label: "I'm not sure" },
    ],
  },
  {
    id: "q5" as const,
    article: "Article 12(4)",
    title: "How long do you retain behavioral logs?",
    subtitle:
      "Article 12(4) mandates a minimum of 6 months. Penalties under Article 73 apply if logs cannot support forensic reconstruction.",
    options: [
      { value: "over1yr", label: "More than 1 year" },
      { value: "6to12mo", label: "6 to 12 months" },
      { value: "under6mo", label: "Less than 6 months" },
      { value: "none", label: "We don't retain logs" },
      { value: "unknown", label: "I'm not sure" },
    ],
  },
  {
    id: "q6" as const,
    article: "Article 12(3)",
    title:
      "Can you query logs and export them in machine-readable format?",
    subtitle:
      "Article 12(3) requires post-market monitoring support — logs must be queryable by time range, actor, and outcome, and exportable for supervisory review.",
    options: [
      {
        value: "full",
        label:
          "Yes — full query capability (by time, actor, category, outcome) with JSONL/CSV export",
      },
      {
        value: "partial",
        label:
          "Partial — we can query but cannot export in machine-readable format",
      },
      {
        value: "none",
        label: "No — logs are stored but not practically queryable",
      },
      { value: "unknown", label: "I'm not sure" },
    ],
  },
  {
    id: "q7" as const,
    article: "Articles 26 & 73",
    title:
      "Can you produce a complete audit trail on regulatory request?",
    subtitle:
      "Article 26 makes deployers responsible for preserving logs. Article 73 requires forensic preservability — gaps here create direct penalty exposure.",
    options: [
      {
        value: "yes",
        label:
          "Yes — we have a defined process and could produce complete audit trails within 72 hours",
      },
      {
        value: "partial",
        label:
          "Partial — we could reconstruct logs but it would require significant manual effort",
      },
      {
        value: "no",
        label:
          "No — we could not reliably produce a complete audit trail on demand",
      },
      { value: "unknown", label: "I'm not sure" },
    ],
  },
];

const COMPLIANCE_ITEMS = [
  {
    id: "q3",
    article: "Article 12(1)",
    requirement: "Automatic & independent behavioral recording",
    agentlairSolution:
      "Middleware-layer interception via ctx.waitUntil() — logging is not invoked by the agent, cannot be suppressed by the agent, adds no latency.",
  },
  {
    id: "q4",
    article: "Articles 12 & 15",
    requirement: "Cryptographic tamper-evidence",
    agentlairSolution:
      "Ed25519 signatures on every entry + SHA-256 hash chain — signed by AgentLair infrastructure, outside agent control. Any modification breaks the chain detectably.",
  },
  {
    id: "q5",
    article: "Article 12(4)",
    requirement: "Minimum 6-month retention",
    agentlairSolution:
      "Starter ($29/mo) retains logs for 1 year. Enterprise up to 7 years. Free tier is 30 days (below the Article 12 minimum by design).",
  },
  {
    id: "q6",
    article: "Article 12(3)",
    requirement: "Queryable, machine-readable log export",
    agentlairSolution:
      "Full query API by time, actor, category, and outcome + JSONL/CSV export + attestation endpoint (CAF format) for supervisory submission.",
  },
  {
    id: "q7",
    article: "Articles 26 & 73",
    requirement: "On-demand audit trail production",
    agentlairSolution:
      "GET /v1/attestations returns verifiable attestation packages in CAF format — designed for regulatory submission. Produced in seconds, not weeks.",
  },
];

function scoreAnswer(qId: string, value: string): RAGStatus {
  switch (qId) {
    case "q3":
      if (value === "independent") return "green";
      if (value === "partial") return "amber";
      if (value === "none") return "red";
      return "amber";
    case "q4":
      if (value === "cryptographic") return "green";
      if (value === "partial") return "amber";
      if (value === "none") return "red";
      return "amber";
    case "q5":
      if (value === "over1yr" || value === "6to12mo") return "green";
      if (value === "under6mo" || value === "none") return "red";
      return "amber";
    case "q6":
      if (value === "full") return "green";
      if (value === "partial") return "amber";
      if (value === "none") return "red";
      return "amber";
    case "q7":
      if (value === "yes") return "green";
      if (value === "partial") return "amber";
      if (value === "no") return "red";
      return "amber";
    default:
      return "amber";
  }
}

function RAGBadge({ status }: { status: RAGStatus }) {
  if (status === "green") {
    return (
      <span className="inline-flex items-center gap-1.5 rounded-full border border-green-500/20 bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-600 dark:text-green-400">
        <Check className="size-3" />
        Compliant
      </span>
    );
  }
  if (status === "amber") {
    return (
      <span className="inline-flex items-center gap-1.5 rounded-full border border-yellow-500/20 bg-yellow-500/10 px-2.5 py-0.5 text-xs font-medium text-yellow-700 dark:text-yellow-400">
        <AlertTriangle className="size-3" />
        Attention Needed
      </span>
    );
  }
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-red-500/20 bg-red-500/10 px-2.5 py-0.5 text-xs font-medium text-red-600 dark:text-red-400">
      <X className="size-3" />
      Non-Compliant
    </span>
  );
}

function ProgressBar({ step }: { step: number }) {
  const pct = Math.round((step / 7) * 100);
  return (
    <div className="mb-8">
      <div className="mb-2 flex items-center justify-between">
        <span className="text-muted-foreground text-xs">
          Question {step} of 7
        </span>
        <span className="text-muted-foreground text-xs">{pct}%</span>
      </div>
      <div className="h-1.5 w-full rounded-full bg-muted">
        <div
          className="h-1.5 rounded-full bg-primary transition-all duration-500"
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

function RadioOption({
  selected,
  onClick,
  label,
}: {
  selected: boolean;
  onClick: () => void;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "w-full rounded-lg border p-4 text-left transition-all",
        selected
          ? "border-primary bg-primary/5 ring-1 ring-primary"
          : "hover:border-primary/40 hover:bg-muted/30",
      )}
    >
      <div className="flex items-start gap-3">
        <div
          className={cn(
            "mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full border-2 transition-colors",
            selected ? "border-primary bg-primary" : "border-muted-foreground/40",
          )}
        >
          {selected && <div className="size-1.5 rounded-full bg-white" />}
        </div>
        <span className="text-sm leading-snug">{label}</span>
      </div>
    </button>
  );
}

function CheckboxOption({
  selected,
  onClick,
  label,
}: {
  selected: boolean;
  onClick: () => void;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "w-full rounded-lg border p-4 text-left transition-all",
        selected
          ? "border-primary bg-primary/5 ring-1 ring-primary"
          : "hover:border-primary/40 hover:bg-muted/30",
      )}
    >
      <div className="flex items-start gap-3">
        <div
          className={cn(
            "mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-sm border-2 transition-colors",
            selected ? "border-primary bg-primary" : "border-muted-foreground/40",
          )}
        >
          {selected && <Check className="size-3 text-white" />}
        </div>
        <span className="text-sm leading-snug">{label}</span>
      </div>
    </button>
  );
}

export function ComplianceAssess() {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Partial<Answers>>({ q1: [] });
  const [email, setEmail] = useState("");
  const [emailSubmitted, setEmailSubmitted] = useState(false);
  const [emailLoading, setEmailLoading] = useState(false);

  const isHighRisk =
    Array.isArray(answers.q1) &&
    answers.q1.length > 0 &&
    !(answers.q1.length === 1 && answers.q1[0] === "none");

  const handleQ1Toggle = (val: string) => {
    const current = answers.q1 || [];
    if (val === "none") {
      setAnswers({
        ...answers,
        q1: current.includes("none") ? [] : ["none"],
      });
    } else {
      const withoutNone = current.filter((v) => v !== "none");
      if (withoutNone.includes(val)) {
        setAnswers({
          ...answers,
          q1: withoutNone.filter((v) => v !== val),
        });
      } else {
        setAnswers({ ...answers, q1: [...withoutNone, val] });
      }
    }
  };

  const setRadioAnswer = (qId: keyof Answers, value: string) => {
    setAnswers({ ...answers, [qId]: value });
  };

  const canAdvance = (): boolean => {
    if (step === 0) return true;
    if (step === 1) return (answers.q1?.length ?? 0) > 0;
    const qId = `q${step}` as keyof Answers;
    return !!(answers[qId] as string | undefined);
  };

  const computeResults = () => {
    const items = COMPLIANCE_ITEMS.map((item) => {
      const ans = answers[item.id as keyof Answers] as string | undefined;
      const status = scoreAnswer(item.id, ans ?? "unknown");
      return { ...item, status };
    });

    const reds = items.filter((i) => i.status === "red").length;
    const ambers = items.filter((i) => i.status === "amber").length;

    let overall: "not-high-risk" | "compliant" | "partial" | "non-compliant";
    if (!isHighRisk) {
      overall = "not-high-risk";
    } else if (reds > 0) {
      overall = "non-compliant";
    } else if (ambers > 0) {
      overall = "partial";
    } else {
      overall = "compliant";
    }

    const weeksToCompliance =
      overall === "compliant" || overall === "not-high-risk"
        ? 0
        : reds > 0
          ? 2
          : 1;

    return { items, reds, ambers, overall, weeksToCompliance };
  };

  const handleEmailSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setEmailLoading(true);
    try {
      await fetch("https://agentlair.dev/v1/compliance-guide", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, source: "eu-ai-act-assess" }),
      });
    } catch {
      // silently succeed — UX should not block on backend availability
    } finally {
      setEmailLoading(false);
      setEmailSubmitted(true);
    }
  };

  // ── INTRO ──────────────────────────────────────────────────────────────────

  if (step === 0) {
    return (
      <section className="py-28 lg:pt-44 lg:pb-32">
        <div className="container max-w-2xl">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border bg-muted/60 px-3 py-1 font-mono text-xs text-muted-foreground">
            <Shield className="size-3 text-primary" />
            EU AI Act Article 12 · Enforcement August 2, 2026
          </div>
          <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
            Article 12 Compliance
            <br className="hidden sm:block" />
            Self-Assessment
          </h1>
          <p className="text-muted-foreground mt-4 text-lg">
            7 questions. 3 minutes. Find out if your AI system meets the
            tamper-evident logging requirements — and exactly what needs to
            change before the deadline.
          </p>

          <div className="mt-8 space-y-3">
            {[
              "Is your system classified as high-risk under Annex III?",
              "Are your logs independent, cryptographically signed, and queryable?",
              "Do you meet the 6-month minimum retention requirement?",
              "Can you produce an audit trail on regulatory request?",
            ].map((item) => (
              <div key={item} className="flex items-start gap-3 text-sm">
                <Check className="mt-0.5 size-4 shrink-0 text-primary" />
                <span>{item}</span>
              </div>
            ))}
          </div>

          <div className="mt-10 flex flex-col gap-3 sm:flex-row sm:items-center">
            <Button size="lg" onClick={() => setStep(1)} className="gap-2">
              Start assessment
              <ArrowRight className="size-4" />
            </Button>
            <a
              href="/eu-ai-act"
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
            >
              Read the full Article 12 overview →
            </a>
          </div>
          <p className="text-muted-foreground mt-3 text-xs">
            No account required. Results shown immediately on completion.
          </p>
        </div>
      </section>
    );
  }

  // ── RESULTS ────────────────────────────────────────────────────────────────

  if (step === 8) {
    const results = computeResults();

    const overallConfig = {
      "not-high-risk": {
        label: "Likely Not High-Risk",
        bg: "bg-blue-500/10",
        border: "border-blue-500/20",
        text: "text-blue-600 dark:text-blue-400",
        Icon: Shield,
        desc: "Based on your answers, your system may not be classified as high-risk under Annex III. However, proactive behavioral logging is considered best practice — and the regulation's scope may expand before 2027.",
      },
      compliant: {
        label: "Article 12 Compliant",
        bg: "bg-green-500/10",
        border: "border-green-500/20",
        text: "text-green-600 dark:text-green-400",
        Icon: Check,
        desc: "Your system meets the Article 12 requirements as described. Verify with legal counsel before the August 2, 2026 enforcement date.",
      },
      partial: {
        label: "Partially Compliant",
        bg: "bg-yellow-500/10",
        border: "border-yellow-500/20",
        text: "text-yellow-700 dark:text-yellow-400",
        Icon: AlertTriangle,
        desc: "Your system meets some Article 12 requirements but has gaps that need to be addressed before the August 2, 2026 enforcement deadline.",
      },
      "non-compliant": {
        label: "Non-Compliant",
        bg: "bg-red-500/10",
        border: "border-red-500/20",
        text: "text-red-600 dark:text-red-400",
        Icon: X,
        desc: `Your system has ${results.reds} critical gap${results.reds !== 1 ? "s" : ""} that must be resolved before August 2, 2026 to avoid penalties of up to €15M or 3% of global turnover.`,
      },
    };

    const cfg = overallConfig[results.overall];

    return (
      <section className="py-28 lg:pt-44 lg:pb-32">
        <div className="container max-w-2xl">
          <button
            onClick={() => setStep(7)}
            className="text-muted-foreground hover:text-foreground mb-6 flex items-center gap-1 text-xs transition-colors"
          >
            <ChevronLeft className="size-3" />
            Back to assessment
          </button>

          <h1 className="text-2xl font-bold tracking-tight md:text-3xl">
            Your Compliance Report
          </h1>
          <p className="text-muted-foreground mt-1 text-sm">
            EU AI Act Article 12 · Based on your answers · Enforcement August
            2, 2026
          </p>

          {/* Overall status */}
          <Card className={cn("mt-6 border", cfg.border, cfg.bg)}>
            <CardContent className="px-5 py-5">
              <div className="flex items-start gap-4">
                <div
                  className={cn(
                    "flex size-10 shrink-0 items-center justify-center rounded-full border",
                    cfg.bg,
                    cfg.border,
                  )}
                >
                  <cfg.Icon className={cn("size-5", cfg.text)} />
                </div>
                <div>
                  <p className={cn("text-lg font-bold", cfg.text)}>
                    {cfg.label}
                  </p>
                  <p className="text-muted-foreground mt-1 text-sm">
                    {cfg.desc}
                  </p>
                  {(results.overall === "non-compliant" ||
                    results.overall === "partial") && (
                    <div className="mt-3 flex items-center gap-2">
                      <Clock className="text-muted-foreground size-4" />
                      <span className="text-muted-foreground text-sm">
                        Estimated time to compliance with AgentLair:{" "}
                        <strong className="text-foreground">
                          {results.weeksToCompliance <= 1
                            ? "~1 week"
                            : `~${results.weeksToCompliance} weeks`}
                        </strong>
                      </span>
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Per-requirement breakdown */}
          <div className="mt-8">
            <h2 className="text-muted-foreground mb-3 text-xs font-semibold uppercase tracking-wide">
              Requirement Breakdown
            </h2>
            <div className="space-y-3">
              {results.items.map((item) => (
                <Card
                  key={item.id}
                  className={cn(
                    "border",
                    item.status === "red" && "border-red-500/20",
                    item.status === "amber" && "border-yellow-500/20",
                    item.status === "green" && "border-green-500/20",
                  )}
                >
                  <CardContent className="px-4 py-4">
                    <div className="flex flex-wrap items-start justify-between gap-2">
                      <div>
                        <span className="text-muted-foreground font-mono text-xs">
                          {item.article}
                        </span>
                        <p className="mt-0.5 text-sm font-medium">
                          {item.requirement}
                        </p>
                      </div>
                      <RAGBadge status={item.status} />
                    </div>
                    {item.status !== "green" && (
                      <div className="bg-muted/40 mt-3 rounded-md px-3 py-2.5">
                        <p className="text-muted-foreground mb-1 text-xs font-medium">
                          How AgentLair addresses this:
                        </p>
                        <p className="text-xs leading-relaxed">
                          {item.agentlairSolution}
                        </p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* CTA */}
          <Card className="border-primary/20 bg-primary/5 mt-8">
            <CardContent className="px-5 py-5">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="font-semibold">Fix your compliance gaps today</p>
                  <p className="text-muted-foreground mt-1 text-sm">
                    AgentLair's audit infrastructure addresses every Article 12
                    requirement out of the box. Free to start — Starter ($29/mo)
                    meets the 6-month retention minimum.
                  </p>
                </div>
                <a
                  href="/quickstart"
                  className="bg-primary text-primary-foreground hover:bg-primary/90 inline-flex shrink-0 items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold transition-colors"
                >
                  Start free
                  <ArrowRight className="size-4" />
                </a>
              </div>
            </CardContent>
          </Card>

          {/* Email capture */}
          <Card className="mt-4">
            <CardContent className="px-5 py-5">
              <div className="flex items-start gap-3">
                <FileText className="text-primary mt-0.5 size-5 shrink-0" />
                <div className="flex-1">
                  <p className="text-sm font-medium">
                    Get the full Article 12 compliance guide
                  </p>
                  <p className="text-muted-foreground mt-0.5 text-xs">
                    Detailed walkthrough of every requirement with
                    implementation examples, regulatory references, and a
                    pre-audit checklist.
                  </p>
                  {emailSubmitted ? (
                    <div className="mt-3 flex items-center gap-2 text-sm text-green-600 dark:text-green-400">
                      <Check className="size-4" />
                      Guide sent to {email}
                    </div>
                  ) : (
                    <form
                      onSubmit={handleEmailSubmit}
                      className="mt-3 flex gap-2"
                    >
                      <Input
                        type="email"
                        placeholder="you@company.com"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        required
                        className="h-9 text-sm"
                      />
                      <Button
                        type="submit"
                        size="sm"
                        disabled={emailLoading}
                        variant="outline"
                      >
                        {emailLoading ? "Sending..." : "Send guide"}
                      </Button>
                    </form>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Footer links */}
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 border-t pt-6">
            <a
              href="/eu-ai-act"
              className="text-primary flex items-center gap-1.5 text-sm hover:underline"
            >
              <Shield className="size-3.5" />
              Full Article 12 overview
            </a>
            <a
              href="/pricing"
              className="text-primary flex items-center gap-1.5 text-sm hover:underline"
            >
              <Zap className="size-3.5" />
              View pricing
            </a>
            <a
              href="/docs"
              className="text-primary flex items-center gap-1.5 text-sm hover:underline"
            >
              <FileText className="size-3.5" />
              Documentation
            </a>
          </div>
        </div>
      </section>
    );
  }

  // ── QUESTION 1 — Multi-select classification ───────────────────────────────

  if (step === 1) {
    return (
      <section className="py-28 lg:pt-44 lg:pb-32">
        <div className="container max-w-2xl">
          <ProgressBar step={1} />
          <button
            onClick={() => setStep(0)}
            className="text-muted-foreground hover:text-foreground mb-6 flex items-center gap-1 text-xs transition-colors"
          >
            <ChevronLeft className="size-3" />
            Back
          </button>
          <div className="text-muted-foreground mb-2 font-mono text-xs">
            Annex III — High-Risk Classification
          </div>
          <h2 className="text-xl font-bold tracking-tight md:text-2xl">
            Is your AI system used in any of these domains?
          </h2>
          <p className="text-muted-foreground mt-2 text-sm">
            EU AI Act Annex III defines the high-risk system categories subject
            to Article 12 obligations. Select all that apply.
          </p>
          <div className="mt-6 space-y-2">
            {HIGH_RISK_DOMAINS.map((domain) => (
              <CheckboxOption
                key={domain.value}
                selected={(answers.q1 || []).includes(domain.value)}
                onClick={() => handleQ1Toggle(domain.value)}
                label={domain.label}
              />
            ))}
          </div>
          <div className="mt-6 flex justify-end">
            <Button
              onClick={() => setStep(2)}
              disabled={!canAdvance()}
              className="gap-2"
            >
              Next
              <ArrowRight className="size-4" />
            </Button>
          </div>
        </div>
      </section>
    );
  }

  // ── QUESTIONS 2–7 — Radio ──────────────────────────────────────────────────

  const qIndex = step - 2;
  const currentQ = RADIO_QUESTIONS[qIndex];
  if (!currentQ) return null;

  const currentAnswer = answers[currentQ.id as keyof Answers] as
    | string
    | undefined;

  return (
    <section className="py-28 lg:pt-44 lg:pb-32">
      <div className="container max-w-2xl">
        <ProgressBar step={step} />
        <button
          onClick={() => setStep(step - 1)}
          className="text-muted-foreground hover:text-foreground mb-6 flex items-center gap-1 text-xs transition-colors"
        >
          <ChevronLeft className="size-3" />
          Back
        </button>
        {currentQ.article && (
          <div className="text-muted-foreground mb-2 font-mono text-xs">
            {currentQ.article}
          </div>
        )}
        <h2 className="text-xl font-bold tracking-tight md:text-2xl">
          {currentQ.title}
        </h2>
        <p className="text-muted-foreground mt-2 text-sm">
          {currentQ.subtitle}
        </p>
        <div className="mt-6 space-y-2">
          {currentQ.options.map((opt) => (
            <RadioOption
              key={opt.value}
              selected={currentAnswer === opt.value}
              onClick={() => setRadioAnswer(currentQ.id, opt.value)}
              label={opt.label}
            />
          ))}
        </div>
        <div className="mt-6 flex justify-end">
          <Button
            onClick={() => setStep(step + 1)}
            disabled={!canAdvance()}
            className="gap-2"
          >
            {step === 7 ? "View my report" : "Next"}
            <ArrowRight className="size-4" />
          </Button>
        </div>
      </div>
    </section>
  );
}
