// ─── Shared OG Rendering Infrastructure ────────────────────────────────────────
//
// Shared by all OG image routes (og-a2a.ts, og-a2a-stats.ts, and future endpoints).
// Holds WASM/font singleton state. Module-level singletons are correct: all routes
// in the same CF Workers isolate share one WASM instance.
//
// Exports: loadBinary, ensureWasm, svgToPng, gradeColor (LeaderboardGrade)
//
// CF Workers deploy note:
//   agentlair-deploy.ts uploads only dist/index.js via CF REST API — binary
//   imports (.wasm, .woff2) are NOT carried over (no Data rules in REST upload).
//   Fallback chain: direct binary import first (works in Bun local dev), then
//   base64-decode from the bundled *-b64.ts asset (works in CF Workers prod).
//   The b64 assets are generated by:
//     scripts/gen-resvg-wasm-b64.ts  → src/assets/resvg-wasm-b64.ts
//     scripts/gen-fonts-b64.ts       → src/assets/fonts-b64.ts

import { initWasm, Resvg } from '@resvg/resvg-wasm';
import type { LeaderboardGrade } from './a2a-leaderboard-job.js';
import { RESVG_WASM_B64 } from '../assets/resvg-wasm-b64.js';
import { INTER_REGULAR_B64, INTER_BOLD_B64 } from '../assets/fonts-b64.js';

// @ts-expect-error — binary imports: WebAssembly.Module in CF Workers, file path string in Bun
import resvgWasm from '@resvg/resvg-wasm/index_bg.wasm';
// @ts-expect-error — binary font import: ArrayBuffer in CF Workers, file path string in Bun
import interRegularWoff2 from '../assets/inter-regular.woff2';
// @ts-expect-error — binary font import: ArrayBuffer in CF Workers, file path string in Bun
import interBoldWoff2 from '../assets/inter-bold.woff2';

// ─── Module-level singletons ─────────────────────────────────────────────────

let wasmReady = false;
let wasmInitPromise: Promise<void> | null = null;
let fontBuffers: Uint8Array[] = [];

// ─── Binary loading ──────────────────────────────────────────────────────────

/**
 * Decode a base64 string to Uint8Array.
 * Works in both Bun (has atob) and CF Workers (has atob).
 */
function b64ToUint8Array(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Load a binary asset.
 * Fallback chain:
 *   1. ArrayBuffer / Uint8Array — direct binary import (CF Workers with Data rules, or test mocks)
 *   2. string — file path (Bun local dev: import resolves to path)
 *   3. null/undefined/falsy — import failed (CF Workers without Data rules); use base64 fallback
 */
export async function loadBinary(imported: unknown, b64Fallback?: string): Promise<Uint8Array> {
  if (imported instanceof ArrayBuffer) return new Uint8Array(imported);
  if (imported instanceof Uint8Array) return imported;
  if (typeof imported === 'string') {
    // Bun/Node: import resolves to file path
    const { readFileSync } = await import('fs');
    return new Uint8Array(readFileSync(imported));
  }
  // Falsy (undefined/null) — binary import unavailable (CF Workers without Data rules).
  // Fall back to base64-bundled asset.
  if (!imported && b64Fallback) {
    return b64ToUint8Array(b64Fallback);
  }
  throw new Error('Unexpected binary import type: ' + typeof imported);
}

// ─── WASM initialization ─────────────────────────────────────────────────────

export async function ensureWasm(): Promise<boolean> {
  if (wasmReady) return true;
  if (wasmInitPromise) {
    await wasmInitPromise;
    return wasmReady;
  }
  wasmInitPromise = (async () => {
    try {
      // Fallback chain:
      //   1. Direct binary import — WebAssembly.Module in CF Workers (with Data rules), Buffer in Bun
      //   2. File path string — Bun local dev
      //   3. Falsy → decode RESVG_WASM_B64 (CF Workers without Data rules, i.e. REST API deploy)
      let wasmInput: any = resvgWasm;
      if (typeof wasmInput === 'string') {
        // Bun: import resolves to path, read the file
        const { readFileSync } = await import('fs');
        wasmInput = readFileSync(wasmInput);
      } else if (!wasmInput) {
        // CF Workers via REST API: binary import is undefined — decode from base64
        wasmInput = b64ToUint8Array(RESVG_WASM_B64);
      }
      await initWasm(wasmInput);
    } catch (e: unknown) {
      // "Already initialized" means another module/test already called initWasm
      if (!(e instanceof Error && e.message.includes('Already initialized'))) {
        return; // genuine failure — WASM not available
      }
    }
    // Load fonts (needed regardless of whether we just initialized or it was already done)
    fontBuffers = [
      await loadBinary(interRegularWoff2, INTER_REGULAR_B64),
      await loadBinary(interBoldWoff2, INTER_BOLD_B64),
    ];
    wasmReady = true;
  })();
  await wasmInitPromise;
  return wasmReady;
}

// ─── SVG → PNG rendering ─────────────────────────────────────────────────────

export function svgToPng(svg: string): Uint8Array {
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: 1200 },
    font: {
      fontBuffers,
      defaultFontFamily: 'Inter',
      loadSystemFonts: false,
    },
  });
  return resvg.render().asPng();
}

// ─── Grade color (LeaderboardGrade: A/B/C/D/F/E) ────────────────────────────
// NOTE: a2a-audit.ts has its own gradeColor for Grade (A-F only) — do NOT merge.
// This version handles the extra 'E' grade (error/unavailable) used in leaderboard.

export function gradeColor(g: LeaderboardGrade): string {
  switch (g) {
    case 'A': return '#4caf50';
    case 'B': return '#8bc34a';
    case 'C': return '#ff9800';
    case 'D': return '#ff5722';
    case 'F': return '#f44336';
    case 'E': return '#9e9e9e';
    default:  return '#9e9e9e';
  }
}
